[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Leif Denby", email = "lcd@dmi.dk"},
]
dependencies = []
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

